### ISSUE TITLE
Error in the code 

### ISSUE THREAD

**Issue by fareh** [Josiah/JJsGeonamesBundle#4]
root@argos-tn:/var/www/c/caue/edp# php app/console cache:clear
PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/c/caue
/edp/src/JJs/Bundle/GeonamesBundle/Command/LoadLocalitiesCommand.php on line 81

Any idea?

**Comment by Josiah** [comment]
My guess is that this is an issue with your PHP version.
